- README.md
- defaults/main.yml
- tasks/main.yml
Remove kernel_settings_bootloader_cmdline from the docs and public
API.
> do not support kernel_settings_bootloader_cmdline

- .travis.yml
- .travis/config.sh
- .travis/custom.sh
- .travis/runblack.sh
- .travis/runcoveralls.sh
- .travis/runflake8.sh
- .travis/runpylint.sh
- .travis/runpytest.sh
- .travis/runshellcheck.sh
- .travis/runsyspycmd.sh
- .travis/utils.sh
- .yamllint_defaults.yml
- tests/install_ansible_for_testing.sh
- tests/install_tuned_for_testing.sh
- tests/run_ansible_for_testing.sh
- tests/setup_module_utils.sh
- tests/tests_bool_not_allowed.yml
- tox.ini
sync with latest template including shellcheck
fix shellcheck issues
fix yamllint issues
> sync with latest template including shellcheck

- .travis/config.sh
@richm, sorry. I forgot `fi` in the previous commit... :(
> Missed "fi" in .travis/config.sh in the previous commit.

- tests/tests_include_vars_from_parent.yml
do not use the case_sensitive argument to the unique filter
> support jinja 2.7

- library/kernel_settings.py
@richm, this is an example of sentence to start the synopsis of module doc. If you could suggest what to put, I'm going to add it to each module. Thanks!
> RHELPLAN-69928  Add a note to each module Doc to indicate it is private

- templates/kernel_settings.j2
BZ#2006230, BZ#2006231, BZ#2006233
> Use {{ ansible_managed | comment }} to fix multi-line ansible_managed

- tests/tests_change_settings.yml
- tests/tests_simple_settings.yml
Add tests::reboot tag to tests/tests_{change,simple}_settings.yml for CI.
> Add tests::reboot tag

- CHANGELOG.md
The file is automatically generated from the git log.
Please feel free to modify it. Thanks.
> CHANGELOG.md - replace the ATX-style with the setext-style for the header H1 and H2.

- .github/workflows/ansible-lint.yml
- .github/workflows/changelog_to_tag.yml
- .github/workflows/codeql.yml
- .github/workflows/tox.yml
- .github/workflows/woke.yml
- .lgtm.yml
- tests/tests_bool_not_allowed.yml
- Workaround a yamllint truthy error in .github/workflows/codeql.yml.
- Remove .lgtm.yml.
> Fixes for the github lgtm / codeql changes

- CHANGELOG.md
[1.1.11] - 2023-01-20
--------------------
- none
- ansible-lint 6.x fixes (#119)
- Cleanup non-inclusive words.
- Add check for non-inclusive language (#117)
- add ubuntu requirements for pyunit tests
- add sanity files for ansible-test 2.13 and 2.14
> Version 1.1.11 - CHANGELOG.md [citest skip]

- CHANGELOG.md
Create changelog update and release for version 1.1.14
> docs(changelog): version 1.1.14 [citest skip]

- CHANGELOG.md
Create changelog update and release for version 1.1.15
> docs(changelog): version 1.1.15 [citest skip]

- CHANGELOG.md
Create changelog update and release for version 1.1.16
> docs(changelog): version 1.1.16 [citest skip]

- CHANGELOG.md
Create changelog update and release for version 1.1.17
> docs(changelog): version 1.1.17 [citest skip]

- .README.html
- CHANGELOG.md
Update changelog and .README.html for version 1.1.18
Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>
> docs(changelog): version 1.1.18 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.1.19
> docs(changelog): version 1.1.19 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.2.2
> docs(changelog): version 1.2.2 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.2.4
> docs(changelog): version 1.2.4 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.2.5
> docs(changelog): version 1.2.5 [citest skip]

- .github/workflows/tft.yml
- **ci: Add tft plan and workflow**
- **ci: Fix tft workflow**
> ci: Fix tft workflow

- .github/workflows/tft.yml
Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>
> ci: Replace / with | in status to distinguish with BaseOS CI tests

- library/kernel_settings_get_config.py
> refactor: fix python black formatting
