linux-system-roles/kernel_settings

tasks/main.yml
The role was overwriting the existing profile file.
Fixed by using the `template` module with `force: no` - if
the profile already exists, do not overwrite with the template
=> do not overwrite existing profile file

README.md
Clarify the precedence of setting parameters with the `kernel_settings`
role vs. using `sysctl` files, the `sysctl` command, `grubby`, etc.
=> clarify precedence of settings w.r.t. sysctl, sysfs, bootloader

library/kernel_settings.py, tests/unit/modules/test_kernel_settings.py
Adds a new return value from the module `reboot_required` - this is
a boolean value, `false` by default.  If `true`, this means there
was a change made that will require rebooting the managed host in
order for the change to take effect.
I added a `RETURN` section to document the module return values.
I cleaned up the formatting of the examples and of the return
messages.
=> module should indicate if reboot needed to apply changes

README.md, defaults/main.yml, library/kernel_settings.py, tests/tuned/etc/tuned/basic_settings/tuned.conf, tests/unit/modules/test_kernel_settings.py, tests/vars/vars_simple_settings.yml
Some of the systems we use for testing have `quiet` as a built-in
bootloader cmdline value.  The kernel_settings role cannot remove
or replace built-in values.  Instead, use `panic` with a value
of `10001` as it is seldom used and applicable to all platforms.
This also gives us a non-string value to use for testing.
There was a bug with using non-string values in blcmdline
values.  This commit also fixes that bug.
=> use panic instead of quiet in blcmd examples, tests

README.md
* cleaned up some of the markdown formatting.
* clarified the use of `state: empty`
* removed a reference to bootloader
* wording improvements
=> cleanup README - fix formatting, improve wording, remove bootloader

LICENSE, library/kernel_settings.py, tests/unit/modules/test_kernel_settings.py
@pcahyna @nhosoi please review
=> use SPDX-License-Identifier: GPL-2.0-or-later instead of GPLv2+

library/kernel_settings.py, tasks/main.yml, tests/unit/modules/test_kernel_settings.py
The use of `omit` with second level or lower values does not
work on ansible 2.7.  The keys are passed to the module with
the value `__omit_token_xxxx`.  Instead, use the value `none`
or some other value which is empty appropriate for the key being
set, and have the module strip all empty values.
=> do not use omit - does not work on nested values with ansible 2.7

README.md, defaults/main.yml, tasks/main.yml, tests/vars/vars_simple_settings.yml, vars/main.yml
In order to remove the setting corresponding to a scalar valued
parameter, set the parameter to the value `{"state":"absent"}`
=> Implement the scalar parameter removal proposal

tests/tests_simple_settings.yml
The test verification needs access to the role private vars from
vars/main.yml.  Using include_vars requires a path which may be
different depending on the packaging.  Instead, rely on a "trick"
with import_role - using `when: false` will include the role, skipping
the explicit tasks, but running the implicit tasks such as loading
the vars and defaults.
=> use import_role instead of include_vars for role vars

tests/tests_simple_settings.yml
The test playbook needs the role private vars to verify the settings.
use include_role with `public: true` so that those vars will be
exported and available to the tests
@nhosoi @pcahyna
=> use include_role with public: true to get role vars

.travis/config.sh
@richm, could it be possible to add this type of logic for the collections format to make tox/travis tests run?
=> install_tuned_for_testing.sh - supporting the collection path.

.travis/config.sh, .travis/runcollection.sh, .travis/utils.sh, library/kernel_settings.py, tox.ini
- Adding .travis/runcollection.sh.
- Enabling collection as part of tox/travis tests.
- Fixing a black error in library/kernel_settings.py.
- Supporting the collections test path in .travis/config.sh.
"$TOPDIR/tests/kernel_settings/install_tuned_for_testing.sh"
=> RHELPLAN-56580 - sync collections related changes from template to kernel_settings role

library/kernel_settings.py, tests/vars/vars_simple_settings.yml
Disable testing bootloader config - this is failing on rhel9 - the
role doesn't support bootloader settings anyway - this will make
testing cleaner.
See also https://bugzilla.redhat.com/show_bug.cgi?id=1944599
=> disable bootloader tests - fails on rhel9

library/kernel_settings.py, tasks/main.yml, templates/get_ansible_managed.j2, tests/tests_simple_settings.yml, tests/unit/modules/test_kernel_settings.py
https://bugzilla.redhat.com/show_bug.cgi?id=2044640
The kernel_settings role needs to generate the tuned.conf with the
correct `ansible_managed` string commented in the same format as
generated by the template module.  The only way to do this is to
invoke the template module via a lookup with an actual template
file.
=> make tuned.conf have correct ansible_managed comment

vars/CentOS_7.yml, vars/RedHat_7.yml, vars/default.yml
tuned recently switched from configobj to configparser.  The role cannot
yet switch to use configparser.  Ensure that the package python-configobj
is present.
=> ensure python-configobj is present

tests/tests_change_settings.yml
Looks like rhel 8.6 dropped `procps-ng` recently, so no `sysctl` command for test playbooks - add it back
=> add sysctl for testing - package procps-ng

tests/tests_include_vars_from_parent.yml, tests/tests_simple_settings.yml
Ensure tests work when using ANSIBLE_GATHERING=explicit
=> make all tests work with gather_facts: false

CHANGELOG.md
[1.1.9] - 2022-07-10
--------------------
- none
- none
- make all tests work with gather_facts: false (#82)
Ensure tests work when using ANSIBLE_GATHERING=explicit
- make min_ansible_version a string in meta/main.yml (#83)
The Ansible developers say that `min_ansible_version` in meta/main.yml
must be a `string` value like `"2.9"`, not a `float` value like `2.9`.
- Add CHANGELOG.md (#84)
=> Version 1.1.9 - CHANGELOG.md [citest skip]

tasks/main.yml, tests/tests_change_settings.yml
Previously the role would only set `kernel_settings_reboot_required`
if the user did not specify `kernel_settings_reboot_ok: true`.
The role will now set `kernel_settings_reboot_required` whenever
the system needs a reboot, and rely on the handler to clear the flag
if the user has set `kernel_settings_reboot_ok: true`.
=> Set the kernel_settings_reboot_required when reboot needed

.github/workflows/woke.yml, CHANGELOG.md, library/kernel_settings.py, tests/unit/modules/test_kernel_settings.py
Add a check for usage of terms and language that is considered
non-inclusive. We are using the woke tool for this with a wordlist
that can be found at
https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/config_files/woke.yml
Clean up non-inclusive words.
- CHANGELOG.md
- library/kernel_settings.py
- tests/unit/modules/test_kernel_settings.py
=> Add check for non-inclusive language

library/kernel_settings.py
library/kernel_settings.py
- This import of module os is redundant, as it was previously imported [on line 191](1).
- This import of module os is redundant, as it was previously imported [on line 195](1).
Signed-off-by: Noriko Hosoi <nhosoi@redhat.com>
=> Fix issues found by CodeQL

templates/get_ansible_managed.j2, templates/kernel_settings.j2
Add role name to the generated config files.
```
```
Note: This information is provided to help customers identify that it was generated by System Roles. It may also be used for future analysis.
=> Fingerprint RHEL System Role managed config files

tasks/main.yml, tasks/verify_settings.yml, tests/tasks/assert_kernel_settings.yml, tests/tasks/assert_kernel_settings_conf_files.yml
ansible-lint now requires the use of `changed_when` even if the
command already uses `when`
=> ansible-lint - use changed_when even if using conditional

tests/tasks/check_header.yml, tests/templates/get_ansible_managed.j2, tests/tests_simple_settings.yml
Add the following files: tests/tasks/check_header.yml and
tests/templates/get_ansible_managed.j2.
Use check_header.yml to check generated files for the ansible_managed
and fingerprint headers.
check_header.yml takes these parameters.  `fingerprint` is required,
and one of `__file` or `__file_content`:
* `__file` - the full path of the file to check e.g. `/etc/realmd.conf`
* `__file_content` - the output of `slurp` of the file
* `__fingerprint` - required - the fingerprint string `system_role:$ROLENAME` e.g.
`__fingerprint: "system_role:postfix"`
* `__comment_type` - optional, default `plain` - the type of comments used
e.g. `__comment_type: c` for C/C++-style comments.  `plain` uses `#`.
See https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_filters.html#adding-comments-to-fi …
=> test: check generated files for ansible_managed, fingerprint

.ansible-lint, .ostree/get_ostree_data.sh, meta/collection-requirements.yml, tasks/main.yml, tasks/set_vars.yml, tests/tasks/assert_kernel_settings_conf_files.yml, tests/tests_change_settings.yml
The dependency on `ansible.utils.update_fact` is causing issue with
some users who now must install that collection in order to run
the role, even if they do not care about ostree.
The fix is to stop trying to set `ansible_facts.pkg_mgr`, and instead
force the use of the ostree package manager with the `package:` module
`use:` option.  The strategy is - on ostree systems, set the flag
`__$ROLENAME_is_ostree` if the system is an ostree system.  The flag
will either be undefined or `false` on non-ostree systems.
Then, change every invocation of the `package:` module like this:
```yaml
- name: Ensure required packages are present
package:
name: "{{ __$ROLENAME_packages }}"
state: present
use: "{{ (__$ROLENAME_is_ostree | d(false)) |
ternary('ansible.posix.rhel_rpm_ostree', omit) }}"
```
This …
=> refactor: improve support for ostree systems

vars/ALP-Dolomite, vars/ALP-Dolomite.yml
Enhancement: Add variables for additional operating system.
Reason: The existing configuration does not cover [SUSE ALP](https://documentation.suse.com/alp/dolomite/html/alp-dolomite/index.html), the default configurations are being used.
Result: Works as expected in the added operating system.
Issue Tracker Tickets (Jira or BZ if any):na
=> ci: Add ALP-Dolomite var file

.github/workflows/ansible-lint.yml, .github/workflows/ansible-managed-var-comment.yml, .github/workflows/ansible-plugin-scan.yml, .github/workflows/ansible-test.yml, .github/workflows/python-unit-test.yml, .yamllint.yml, tests/tests_change_settings.yml
The latest version of virtualenv does not support creating
python 2.7 virtualenvs.  Change our CI tests to restrict the version
of virtualenv<20.22.0 and tox<4.15 for py27 environments
Move pylint, flake8, and black checks to the py310 environment
which is currently supported by ansible-core 2.17 and its related
checkers such as ansible-lint and ansible-test
pylint now uses ansible-core 2.17 and restricts the version of
pylint to 3.1.0 which is the version used by ansible-test 2.17
Remove `extends: default` for .yamllint.yml.  The latest version
of ansible-lint will automatically incorporate local yamllint
settings unless there is an `extends:`.
The above changes require some fixes to the role code.
For more information, see
https://github.com/linux-system-roles/tox-lsr/pull/168
and …
=> ci: tox-lsr 3.4.0 - fix py27 tests; move other checks to py310

.ostree/packages-runtime-CentOS-10.txt, .ostree/packages-runtime-RedHat-10.txt, .ostree/packages-testing-CentOS-10.txt, .ostree/packages-testing-RedHat-10.txt, meta/main.yml
According to the Ansible team, support for listing platforms in
role `meta/main.yml` files is being removed.
Instead, they recommend using `galaxy_tags`
https://github.com/ansible/ansible/blob/stable-2.17/changelogs/CHANGELOG-v2.17.rst
"Remove the galaxy_info field platforms from the role templates"
https://github.com/ansible/ansible/issues/82453
Many roles already have tags such as "rhel", "redhat", "centos", and "fedora".
I propose that we ensure all of the system roles have these tags.
Some of our roles support Suse, Debian, Ubuntu, and others.
We should add tags for those e.g. the ssh role already has tags for "debian" and "ubuntu".
In addition - for each version listed under `platforms.EL` - add a tag like `elN`.
Q: Why not use a delimiter between the platform and the version e.g. …
=> fix: add support for EL10

.github/workflows/tft.yml
This change is for running tests in Testing Farm CI. This is a replacement for
BaseOS CI that we are currently using. Running it Testing Farm gives us more
control.
It adds a workflow for running tests, and a plans directory containing a test
plan and a README-plans.md with some info.
Note that this workflow runs from the main branch. This means that changes to
the workflow must be merged to main, then pull requests will be able to run it.
This is because the workflow uses on: issue_comment context, this is a security
measure recommended by GitHub. It saves us from leaking organization secrets.
The functionality is WIP, so await future fixes and updates.
Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>
=> ci: Improve tft plan and workflow

README.md, defaults/main.yml, tasks/main.yml, tasks/set_vars.yml, tests/vars/tests_SL-Micro.yml, vars/ALP-Dolomite, vars/ALP-Dolomite.yml
Enhancement: - Added a block to identify and handle reboots for transactional update systems on package changes. Update README. Remove ALP-Dolomite var as it is no longer used.
Reason: Ensure necessary reboots are managed, as changes on transactional update systems are applied in a separate snapshot and require a reboot to take effect.
Result: Manages system reboots for transactional update systems when a package is installed.
Issue Tracker Tickets (Jira or BZ if any):na
=> ci: Handle reboot for transactional update systems

tasks/main.yml
tuned 2.23 introduced a new profile directory, and the ability to
change that directory.  The role will now look for the profile
directory among a few candidates.
=> fix: detect profile parent directory

.github/workflows/tft.yml, .github/workflows/tft_citest_bad.yml, contributing.md
* Add "BusinessUnit": "system_roles" environment setting to tag our jobs in Testing farm
* Add tmt_plan_filter to run additional workflows besides general
* Allow more [citest bad] comment formats
* Get memory and supported platforms info from the PR ref
* Move LINUXSYSTEMROLES_USER to vars and use it everywhere in tft.yml
* Remove extra GITHUB_ORG definition
Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>
=> ci: Add tags to TF workflow, allow more [citest bad] formats

.github/workflows/ansible-test.yml, .github/workflows/tft.yml
The ansible-test github action does not use a supported version
of ansible-core by default.
https://github.com/ansible-community/ansible-test-gh-action?tab=readme-ov-file#ansible-core-version
We have to set it in our action.  Using `stable-2.17` as that is the latest stable version.
=> ci: ansible-test action now requires ansible-core version

tests/vars/rh_distros_vars.yml, vars/CentOS_7.yml, vars/main.yml
We have a lot of requests to support Rocky and Alma in various system roles. The
first part of adding support is adding `vars/` files for these platforms. In
almost every case, for a given major version N, the vars file RedHat_N.yml can
be used for CentOS, Rocky, and Alma.  Rather than making a copy of the
RedHat_N.yml file, just use a symlink to reduce size and maintenance burden, and
standardize this across all system roles for consistency.
NOTE: There is no Alma or Rocky version 7 or less.
NOTE: OracleLinux is not a strict clone, so we are not going to do this for
OracleLinux at this time.  Support for OracleLinux will need to be done in
separate PRs. For more information, see
https://github.com/linux-system-roles/cockpit/issues/130
**Question**: Why not just use …
=> refactor: Use vars/RedHat_N.yml symlink for CentOS, Rocky, Alma wherever possible
